### PR TITLE
Fixup logging usage

### PR DESCRIPTION
**Pull request by Gr1N**
Hello!

Fixed logging usage. Very small fix, but, for example, now we can configure logging just for `cron-descriptor` package.

### CODE REVIEW

**Comment by Salamek** [comment]
Looks ok to me

**Comment by Gr1N** [comment]
Thanks! Could you please publish new version of package on PyPI?

**Comment by Salamek** [comment]
@Gr1N 1.2.8 is out

**Comment by Gr1N** [comment]
@Salamek many thanks!

**Pull request merged**
